# Generated by Django 3.1.7 on 2021-04-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='sit_count',
            field=models.IntegerField(null=True),
        ),
    ]
