# Generated by Django 3.1.7 on 2021-04-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210406_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='sitter_pic',
        ),
    ]
