# Generated by Django 3.1.7 on 2021-04-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210402_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_sitter',
            field=models.BooleanField(default=False),
        ),
    ]
