# Generated by Django 3.1.7 on 2021-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210406_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='is_interested',
            field=models.BooleanField(default=False),
        ),
    ]
