# Generated by Django 3.1.7 on 2021-04-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210403_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='sitter',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='owner',
            name='about',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='about',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
