# Generated by Django 3.1.7 on 2021-04-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sitter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
