# Generated by Django 3.1.7 on 2021-04-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_photo_sitter_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitterPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sitter')),
            ],
        ),
    ]
