# Generated by Django 3.1.7 on 2021-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210405_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='sitter',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
